### PR TITLE
Changes to accomodate requests and fixed images

### LINKED ISSUE #3: Replace urllib with requests
Replace [urllib](https://docs.python.org/3/library/urllib.html) with [requests](http://docs.python-requests.org/en/master/) so that we don't have to worry about differences between python2 & python3 as well as SSL stuff. It does a bunch more than what we need, but whatever.

`pip3 install requests`

See https://stackoverflow.com/a/15035210/4616655 for implementation details.

### PR DESCRIPTION
**Pull request by jn7070**
Closes #3 

Changed from urllib to requests.
From before, changed method of grabbing images from web page for each student.

### CODE REVIEW

**Review by holzbh — CHANGES_REQUESTED** [review]
In WSL 2018:

Looks like I'm having an SSL issue now (I'm happy to install / update any packages, but we should be careful to document any minimum dependencies).

The bigger issue I see is that this failure happens attempting to grab `web_tab_corner_right.gif` which sounds like a layout element. I'll try and look at this independently as well on Monday.

>Traceback (most recent call last):
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>    chunked=chunked)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
>    self._validate_conn(conn)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>    conn.connect()
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
>    ssl_context=context)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
>    return context.wrap_socket(sock, server_hostname=server_hostname)
>  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
>    _context=self)
>  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
>    self.do_handshake()
>  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
>    self._sslobj.do_handshake()
>  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
>    self._sslobj.do_handshake()
>ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
>    timeout=timeout
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>    _stacktrace=sys.exc_info()[2])
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
>    raise MaxRetryError(_pool, url, error or ResponseError(cause))
>urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sis.rpi.edu', port=443): Max retries exceeded with url: /wtlgifs/web_tab_corner_right.gif (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "SIS_Images_Scraper.py", line 223, in <module>
>    getInfoFromCourse(driver)
>  File "SIS_Images_Scraper.py", line 211, in getInfoFromCourse
>    saveImagesToFolder(term, course, class_list)
>  File "SIS_Images_Scraper.py", line 110, in saveImagesToFolder
>    r = requests.get(img_url)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/api.py", line 72, in get
>    return request('get', url, params=params, **kwargs)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
>    return session.request(method=method, url=url, **kwargs)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
>    resp = self.send(prep, **send_kwargs)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
>    r = adapter.send(request, **kwargs)
>  File "/home/[redacted]/.local/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
>    raise SSLError(e, request=request)
>requests.exceptions.SSLError: HTTPSConnectionPool(host='sis.rpi.edu', port=443): Max retries exceeded with url: /wtlgifs/web_tab_corner_right.gif (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))

**Comment by MasterOdin** [comment]
@holzbh, can you try installing `requests[security]` and seeing if you still get the SSL errors.

**Comment by holzbh** [comment]
@MasterOdin Good thought, but the result was the same down to the line numbers. The SSLError is slightly different now, but is still a "bad handshake".

>requests.exceptions.SSLError: HTTPSConnectionPool(host='sis.rpi.edu', port=443): Max retries exceeded with url: /wtlgifs/web_tab_corner_right.gif (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))

**Comment by MasterOdin** [comment]
Exact version of python that you're using?

**Comment by holzbh** [comment]
WSL:
Python 3.5.2 (default, Nov 23 2017, 16:37:01)

Windows:
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32

Both see the same behavior.

**Comment by MasterOdin** [comment]
Ugh, so I was wrong in that moving to requests actually probably made the problem "worse" for more versions of Python due to the fact that SIS doesn't implement [any modern secure ciphers for TLS](https://www.ssllabs.com/ssltest/analyze.html?d=sis.rpi.edu) and because requests is updated regularly (and then the builtin python urllib semi-regularly), it drops support for insecure ciphers unless explicitly asked for.

The solution here is to re-add an insecure cipher for Requests to use `requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS = 'DES-CBC3-SHA'` (put a comment above this explaining that this is a weak cipher, but it's necessary for accessing SIS via requests and see https://www.ssllabs.com/ssltest/analyze.html?d=sis.rpi.edu for why we can't use something more modern) and maybe also ask RPI to upgrade the systems that SIS are on to accept more modern ciphers?

Example of getting SIS to work with requests (notice the 200 response after setting the cipher):
```
Python 3.5.2 (default, Jun  4 2018, 00:50:17)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://sis.rpi.edu')
Traceback (most recent call last):
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sis.rpi.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mpeveler/.pyenv/versions/3.5.2/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sis.rpi.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)'),))
>>> requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS = 'DES-CBC3-SHA'
>>> requests.get('https://sis.rpi.edu')
<Response [200]>
```

**Comment by MasterOdin** [comment]
So in working more with Buster, it seems that we really should actually send a polite email to RPI to ask them to upgrade SIS as otherwise people on newer systems are not going to be able to programmatically interface with SIS without having to compile openssl themselves. This is due to the fact openssl 1.1 has removed a bunch of insecure and weak ciphers from being available (all of the ciphers SIS support fall into this category). For example, neither Ubuntu 18.04 or Debian 9 can access SIS via curl and the default openssl.

We'd then probably want to potentially create a Dockerfile to give instructors on those OSes a way to still run this tool (headless chrome should run happily within a docker container, and then just need to mount a volume to the docker container when running it to get the pictures off of it once it's done running), but that should be a separate issue. Let's for now operate under the belief all instructors are using OpenSSL 1.0.x natively.

Additionally, it seems that pyOpenSSL (which gets installed as part of `requests[security]`) includes its own copy of openssl 1.1 inside of it. So, to prevent that for any user that has downloaded `requests[security]`, we'll want to do:
```
from urllib3.contrib import pyopenssl
pyopenssl.extract_from_urllib3()
```
after importing requests to disable pyOpenSSL and to use the builtin openssl.

What a mess!

**Comment by holzbh** [comment]
All the selenium calls now do the right SSL thing, but I get handshake issues with the requests call that's actually saving the image still. Also still has a debug print in there, in case debugging needs to happen on a non-alum instructor's account (e.g. @bmcutler's account). This should be removed before merge. Still not quite ready for a merge, but closer. 

Also see @MasterOdin's comment above. If we do incorporate that, first test that it works on a system that does pyopenssl, and then wrap it in a try/except ImportError where the except just does `pass` so the script doesn't blowup on systems that _don't_ have pyopenssl installed.

It's also probably better to move towards searching for an image tag containing `apex` or `apex.cct.rpi.edu` or something like that. Would be less fragile than if the layout ever was to change and now there's 3 transparent images between the header row and the actual student image, etc. Of course SIS making changes like that is unlikely, so it's not a big deal if we just stick to the more arcane "count the img tags" method and examine the `NAME` attribute.

**Pull request merged**
